[package]
authors = ["Ogbonda Chiziaruhoma<chiziaruhoma@gmail.com>"]
edition = "2018"
name = "hummer-ffi"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "staticlib"]
name = "hummer_ffi"

[dependencies]
hummer = {path = "../hummer"}


[build-dependencies]
cbindgen = "0.14.3"
dart-bindgen = "0.1"
